urls.py
from django.conf.urls.defaults import *
from django.conf import settings

urlpatterns = patterns('',
    url('login', include('users.urls')),
    url('^auth/', include('users.urls')),
    url('^wall/$', include('wall.urls')),
    url('^photo/$', include('photo.urls')),
    url('^LOAD/$', include('LOAD.urls')),
    url('^RESET/$', include('RESET.urls')),
    url('^SEARCH/$', include('wall.urls')),
      
)

if settings.DEBUG:
    urlpatterns += patterns('django.views.static',
        (r'^media/(?P<path>.*)$', 'serve',
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    )



#http://<home>/SEARCH?user=<u>&type=<t>&scope=<s>&terms=<tm>

wall/urls.py
from django.conf.urls.defaults import patterns, url,include
from users.views import login

urlpatterns = patterns('wall.views',
    #url(r'^login/$', 'login', name='login')
    #url(r'^/?$', 'timeline', name='timeline'),
    #url(r'^public/$', 'publicline', name='publicline'),
    #url(r'^(?P<username>\w+)/$', 'userline', name='userline'),
    #url(r'^/?$', 'userline', name='userline'),
    url('', 'userline',name='user'),
)
    #url(r'^?user=$(?P<user>\w{4}\d{1,2,3})&/type=(?P<type>\w{4,5})&/scope=(?P<scope>\w{4})&/terms=(?P<terms>(\w\+)+)$', 'userline',name='user'),
#(?P<user>\w{4}\d{1,2,3})&/type=(?P<type>\w{4,5})&/scope=(?P<scope>\w{4})&/terms=(?P<terms>\w+)$


#http://<home>/SEARCH?user=<u>&type=<t>&scope=<s>&terms=<tm>

wall/forms.py
from django import forms

class WallForm(forms.Form):
    body = forms.CharField(max_length=140)

wall/views.py
import uuid

from django.shortcuts import render_to_response
from django.template import RequestContext
from django.http import HttpResponseRedirect, Http404
from django.core.urlresolvers import reverse

from wall.forms import WallForm

import cass

NUM_PER_PAGE = 200


def timeline(request):
    form = WallForm(request.POST or None)
    if request.user['is_authenticated'] and form.is_valid():
        tweet_id = str(uuid.uuid1())
        cass.save_tweet(tweet_id, request.session['username'], {
            'username': request.session['username'],
            'body': form.cleaned_data['body'],
        })
        return HttpResponseRedirect(reverse('timeline'))
    start = request.GET.get('start')
    if request.user['is_authenticated']:
        tweets,next = cass.get_timeline(request.session['username'],
            start=start, limit=NUM_PER_PAGE)
    else:
        tweets,next = cass.get_userline(cass.PUBLIC_USERLINE_KEY, start=start,
            limit=NUM_PER_PAGE)
    context = {
        'form': form,
        'tweets': tweets,
        'next': next,
    }
    return render_to_response('wall/timeline.html', context,
        context_instance=RequestContext(request))

def publicline(request):
    start = request.GET.get('start')
    tweets,next = cass.get_userline(cass.PUBLIC_USERLINE_KEY, start=start,
        limit=NUM_PER_PAGE)
    context = {
        'tweets': tweets,
        'next': next,
    }
    return render_to_response('wall/publicline.html', context,
        context_instance=RequestContext(request))
"""
def userline(request):
    username = request.session['username']
    menu=1
    try:
        passwd = cass.get_passwd(username)
    except cass.DatabaseError:
        raise Http404
    
    # Query for the friend ids
    friend_usernames = []
    friend_usernames = cass.get_friend(username) + [username]
    
    # Add a property on the user to indicate whether the currently logged-in
    # user is friends with the user
    user['friend'] = username in friend_usernames
    
    
    limit = request.GET.get('start')
    #print "got this from html:",limit
    if not limit:
        limit='200'
    
    posts,next = cass.get_wall(username, limit=limit)
    context = {
        'user': username,
        'username': username,
        'posts': posts,
        'next': next,
        'menu':menu
    }
    
    return render_to_response('wall/userline.html', context,
        context_instance=RequestContext(request))



  """          

def userline(request):
    #http://<home>/SEARCH?user=<u>&type=<t>&scope=<s>&terms=<tm>  scope=user, snet, or glob
    user= request.GET.get('user','')
    type=request.GET.get('type','')
    scope= request.GET.get('scope','')
    terms=request.GET.get('terms','')
    
    
    
    print user,type,scope,terms
    
    print "inside search query"
    photos=[]
    
    if type=='photo':
        if scope=='user':
            object_list=cass.query_photo_index_user(user,terms)
            
        elif scope=='snet':
            object_list=cass.query_photo_index_group(user,terms)
            
        elif scope=='glob':
            object_list=cass.query_photo_index_global(user,terms)
            
    
    elif type=='post':
        if scope=='user':
            object_list=cass.query_post_index_user(user,terms)
            
        elif scope=='snet':
            object_list=cass.query_post_index_group(user,terms)
            
        elif scope=='glob':
            object_list=cass.query_post_index_global(user,terms)
            

            
    context = {
            'user': user,
            'username':user,
            'posts': object_list,
            'type':type,
            #'next': next,
            'menu':menu
        }
        
    return render_to_response('wall/search.html', context,
            context_instance=RequestContext(request))
         
     

    

templates/wall/publicline.html
{% extends "base.html" %}

{% block title %}Public Timeline - {{ block.super }}{% endblock %}

{% block content %}
    <h2 class="grid_4 suffix_5">Public Timeline</h2>
    <ul id="timeline" class="grid_9 alpha">
        {% for tweet in tweets %}
            <li>
                <a href="{% url userline tweet.username %}" class="username">{{ tweet.username }}</a>
                <span class="body">{{ tweet.body|urlize }}</span>
            </li>
        {% empty %}
            <li>There are no tweets yet.  Make sure to post one!</li>
        {% endfor %}
        {% if next %}
            <li class="more"><a href="?start={{ next }}">More</a></li>
        {% endif %}
    </ul>
{% endblock %}

templates/wall/search.html
    <h2> Results of {{ username }}&rsquo;s {{type}} Query: </h2>
    
             
	 {% for post in posts %}
	   {% if type == 'post' %}
            <li>
                <span>{{ post|urlize }}</span>
            </li>
	  {% else %}
	    <li>
                <span><img height="100" width="100" src="{{ MEDIA_URL }}photos/{{post}}.jpg"/></span> 
            </li>
	  {% endif %}
        {% empty %}
            <li>There are no posts yet.  Make sure to post one!</li>
        {% endfor %}
        {% if next %}
            <li class="more"><a href="?start={{ next }}">More</a></li>
        {% endif %}
    </ul>

templates/wall/timeline.html
{% extends "base.html" %}

{% block title %}My Timeline - {{ block.super }}{% endblock %}

{% block content %}
    {% if request.user.is_authenticated %}
        <form method="POST" id="poster">
            <div class="grid_9 alpha">
                <textarea maxlength="140" name="body" type="text" id="id_body"></textarea>
            </div>
            <input type="submit" value="Post Tweet" class="grid_3 omega">
            <div class="clear"></div>
        </form>
    {% else %}
        <h2 class="grid_4 suffix_5">Public Timeline</h2>
    {% endif %}
    <ul id="timeline" class="grid_9 alpha">
        {% for tweet in tweets %}
            <li>
                <a href="{% url userline tweet.username %}" class="username">{{ tweet.username }}</a>
                <span class="body">{{ tweet.body|urlize }}</span>
            </li>
        {% empty %}
            <li>There are no tweets yet.  Make sure to post one!</li>
        {% endfor %}
        {% if next %}
            <li class="more"><a href="?start={{ next }}">More</a></li>
        {% endif %}
    </ul>
{% endblock %}

{% block sidebar %}
    {% if not request.user.is_authenticated %}
        <a href="{% url login %}">Log in to post a tweet</a>
    {% endif %}
{% endblock %}

templates/wall/userline.html
{% extends "base.html" %}

{% block title %}{{ username }} - {{ block.super }}{% endblock %}

{% block content %}
    <h2 class="grid_4 suffix_5">{{ username }}&rsquo;s Wall</h2>
    <ul id="timeline" class="grid_9 alpha">
             
	 {% for post in posts %}
	   {% if post.type == '0' %}
            <li>
                <span class="username"><b><font color="red">{{ post.userid }}</font></b></span>
                <span class="body">{{ post.body|urlize }}</span>
            </li>
	  {% else %}
	    <li>
                <span class="username"><b><font color="red">{{ post.0.1 }}</font></b></span>
                <span class="body"><img height="50" width="50" src="data:image/gif;base64,{{ post.2.1 }}"/></span> 
            </li>
	  {% endif %}
        {% empty %}
            <li>There are no posts yet.  Make sure to post one!</li>
        {% endfor %}
        {% if next %}
            <li class="more"><a href="?start={{ next }}">More</a></li>
        {% endif %}
    </ul>
{% endblock %}

{% block sidebar %}
        {% ifnotequal request.user.id user.id %}
            <form method="POST" action="{% url modify_friend %}?next={{ request.path }}">
                <input type="hidden" name="{% if user.friend %}remove{% else %}add{% endif %}-friend" value="{{ user.id }}" />
                <input type="submit" value="{% if user.friend %}Remove{% else %}Add{% endif %} Friend" />
            </form>
        {% endifnotequal %}    
{% endblock %}